# Generated by Django 4.2.3 on 2023-08-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
