# Generated by Django 4.2.3 on 2023-08-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='last_modified',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='date_posted',
            new_name='published',
        ),
    ]
