# Generated by Django 4.2.3 on 2023-08-13 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_article_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author_id',
            new_name='author',
        ),
    ]
